config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  get "search" => "searches#search"
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
  resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "home/about"=>"homes#about"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
   @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      render :bookcommenter
    else
      @book = Book.find(params[:book_id])
      @user = @book.user
      @newbook = Book.new
      @book_comment = BookComment.new
      render 'books/show'
    end
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    if @book_comment.user == current_user
      BookComment.find(params[:id]).destroy
      @book = Book.find(params[:book_id])
      render :bookcommenter
    end
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_bookcommenter.html.erb
<% if book.book_comments.present? %>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td><%= image_tag book_comment.user.get_profile_image(100,100) %></td>
      <td><%= book_comment.user.name %></td>
      <td><%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %></td>
          <% if book_comment.user == current_user %>
            <td><%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %></td>
          <% end %>
    </tr>
  <% end %>
<% end %>

app/views/book_comments/_bookform.html.erb
<%= form_with model: [@book, @book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5', class: "w-100" %>
    <%= f.submit "送信" %>
<% end %>

app/views/book_comments/bookcommenter.js.erb
$("#comments_area").html("<%= j(render 'book_comments/bookcommenter', book: @book, bookcomment: @book_comment) %>");
$("textarea").val('');